// react-crud/react-crud-frontend/src/components/DeleteUser.tsx
import { useCollection, useQuery } from '@squidcloud/react';

type User = { id: string; email: string; age: number };

export default function DeleteUser({ id }: { id: string }) {
  const collection = useCollection<User>('users');
  const users = useQuery(collection.query());

  const onClick = () => {
    // Find the user with the matching id
    const user = users.data.find((user) => user.data.id == id);

    if (user) {
      user
        .delete()
        .then(() => console.log(`User ${id} deleted`))
        .catch((error) => console.error('Failed to delete user', error));
    }
  };

  return (
    <button id="delete" onClick={onClick}>
      Delete user
    </button>
  );
}

// angular-crud/angular-crud-frontend/src/app/delete-user/delete-user.component.ts
import { Component, Input } from '@angular/core';
import { Squid } from '@squidcloud/client';

type User = { id: string; email: string; age: number };

@Component({
  selector: 'delete-user',
  template: `<div><button (click)="deleteUser()">Delete user</button></div>`,
  styleUrls: ['./delete-user.component.scss'],
})
export class DeleteUserComponent {
  constructor(private readonly squid: Squid) {}

  @Input() id = '';
  /* Accesses the 'users' collection and deletes the user with the specified inputId */
  async deleteUser(): Promise<void> {
    await this.squid.collection<User>('users').doc(this.id).delete();
  }
}
